-- Criação da tabela para armazenar os leads
CREATE TABLE public.leads_funil_1 (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  lead_name TEXT,
  whatsapp TEXT NOT NULL,
  instagram_username TEXT,
  instagram_bio TEXT,
  instagram_followers INT,
  industry TEXT,
  obstacles TEXT[], -- Armazena os obstáculos como um array de strings
  diagnostic_summary TEXT,
  status TEXT,
  msg_enviada_wpp BOOLEAN
);

-- Adiciona comentários para clareza
COMMENT ON TABLE public.leads_funil_1 IS 'Tabela para armazenar informações dos leads capturados na landing page.';
COMMENT ON COLUMN public.leads_funil_1.lead_name IS 'Nome fornecido pelo lead no formulário.';
COMMENT ON COLUMN public.leads_funil_1.whatsapp IS 'Número do WhatsApp do lead.';
COMMENT ON COLUMN public.leads_funil_1.instagram_username IS 'Nome de usuário do Instagram do lead.';
COMMENT ON COLUMN public.leads_funil_1.instagram_bio IS 'Biografia do perfil do Instagram do lead.';
COMMENT ON COLUMN public.leads_funil_1.instagram_followers IS 'Número de seguidores do lead no Instagram.';
COMMENT ON COLUMN public.leads_funil_1.industry IS 'Setor de atuação selecionado pelo lead.';
COMMENT ON COLUMN public.leads_funil_1.obstacles IS 'Array com os obstáculos selecionados pelo lead.';
COMMENT ON COLUMN public.leads_funil_1.diagnostic_summary IS 'Resumo do diagnóstico personalizado gerado pela IA.';
COMMENT ON COLUMN public.leads_funil_1.status IS 'Status do lead no funil de vendas.';
COMMENT ON COLUMN public.leads_funil_1.msg_enviada_wpp IS 'Indica se a mensagem foi enviada via WhatsApp.';
